# Generated by Django 3.0.8 on 2020-08-14 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=50)),
                ('building', models.IntegerField()),
                ('housing', models.IntegerField()),
                ('entrance', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('room', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('passport', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименовние')),
                ('code', models.CharField(max_length=50, verbose_name='Код')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('cost', models.FloatField(verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='GoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование типа')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
                ('short_name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name='Ссылка')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Contact', verbose_name='Контакт')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Contact', verbose_name='Контакт')),
            ],
        ),
        migrations.CreateModel(
            name='GoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.GoodCategory')),
            ],
        ),
        migrations.CreateModel(
            name='GoodPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Address', verbose_name='Адрес')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Contact', verbose_name='Контакт')),
                ('place_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.PlaceType', verbose_name='Тип места')),
            ],
        ),
        migrations.CreateModel(
            name='GoodCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(default=0.0, verbose_name='Количество')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Good', verbose_name='Товар')),
                ('good_place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.GoodPlace', verbose_name='Местонахождение')),
            ],
        ),
        migrations.CreateModel(
            name='GoodCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(verbose_name='Цена товара')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Good', verbose_name='Товар')),
                ('good_place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.GoodPlace', verbose_name='Месторасположение товара')),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.GoodCategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='good',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.GoodType', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='good',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Unit', verbose_name='Единица измерения'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=50, verbose_name='Должность')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Address', verbose_name='Адрес сотрудника')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Contact', verbose_name='Контакт сотрудника')),
                ('job_place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.GoodPlace', verbose_name='Место работы')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, verbose_name='Электронная почта')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Contact', verbose_name='Контакт')),
            ],
        ),
    ]
