# Generated by Django 3.0.8 on 2020-08-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='entrance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='floor',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='housing',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='room',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='passport',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание товара'),
        ),
    ]
