# Generated by Django 3.0.8 on 2020-08-14 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200815_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodSubjectArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'goods subject area',
            },
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='goodcategory',
            options={'verbose_name_plural': 'goods categories'},
        ),
        migrations.AlterModelOptions(
            name='goodcost',
            options={'verbose_name_plural': 'goods cost'},
        ),
        migrations.AlterModelOptions(
            name='goodcount',
            options={'verbose_name_plural': 'goods count'},
        ),
        migrations.AlterModelOptions(
            name='goodplace',
            options={'verbose_name_plural': 'goods place'},
        ),
        migrations.AlterModelOptions(
            name='goodtype',
            options={'verbose_name_plural': 'goods types'},
        ),
        migrations.RemoveField(
            model_name='good',
            name='category',
        ),
        migrations.AlterField(
            model_name='email',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Contact', verbose_name='контакт'),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.CharField(max_length=100, verbose_name='электронная почта'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Address', verbose_name='адрес сотрудника'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Contact', verbose_name='контакт сотрудника'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.GoodPlace', verbose_name='место работы'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position_name',
            field=models.CharField(max_length=50, verbose_name='должность'),
        ),
        migrations.AlterField(
            model_name='good',
            name='code',
            field=models.CharField(max_length=50, verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='good',
            name='cost',
            field=models.FloatField(verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.TextField(null=True, verbose_name='описание товара'),
        ),
        migrations.AlterField(
            model_name='good',
            name='name',
            field=models.CharField(max_length=300, verbose_name='наименовние'),
        ),
        migrations.AlterField(
            model_name='good',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.GoodType', verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='good',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Unit', verbose_name='единица измерения'),
        ),
        migrations.AlterField(
            model_name='goodcost',
            name='cost',
            field=models.FloatField(verbose_name='цена товара'),
        ),
        migrations.AlterField(
            model_name='goodcost',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Good', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='goodcost',
            name='good_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.GoodPlace', verbose_name='месторасположение товара'),
        ),
        migrations.AlterField(
            model_name='goodcount',
            name='count',
            field=models.FloatField(default=0.0, verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='goodcount',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Good', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='goodcount',
            name='good_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.GoodPlace', verbose_name='местонахождение'),
        ),
        migrations.AlterField(
            model_name='goodplace',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Address', verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='goodplace',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Contact', verbose_name='контакт'),
        ),
        migrations.AlterField(
            model_name='goodplace',
            name='name',
            field=models.CharField(max_length=300, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='goodplace',
            name='place_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.PlaceType', verbose_name='тип места'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Contact', verbose_name='контакт'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=models.CharField(max_length=30, verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='placetype',
            name='name',
            field=models.CharField(max_length=30, verbose_name='наименование типа'),
        ),
        migrations.AlterField(
            model_name='url',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Contact', verbose_name='контакт'),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.TextField(verbose_name='ссылка'),
        ),
        migrations.AddField(
            model_name='goodcategory',
            name='subject_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.GoodSubjectArea', verbose_name='предметная область'),
        ),
    ]
