# Generated by Django 3.0.8 on 2020-08-15 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200815_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='наименование валюты')),
                ('short_name', models.CharField(max_length=3, verbose_name='код')),
            ],
            options={
                'verbose_name_plural': 'currency',
            },
        ),
        migrations.RemoveField(
            model_name='good',
            name='cost',
        ),
        migrations.AddField(
            model_name='goodcost',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Currency', verbose_name='валюта'),
        ),
    ]
