# Generated by Django 3.0.8 on 2020-08-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200815_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='building',
            field=models.IntegerField(verbose_name='номер здания'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=30, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=30, verbose_name='страна'),
        ),
        migrations.AlterField(
            model_name='address',
            name='entrance',
            field=models.IntegerField(blank=True, null=True, verbose_name='подъезд'),
        ),
        migrations.AlterField(
            model_name='address',
            name='floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='этаж'),
        ),
        migrations.AlterField(
            model_name='address',
            name='housing',
            field=models.IntegerField(blank=True, null=True, verbose_name='корпус'),
        ),
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(max_length=30, verbose_name='область'),
        ),
        migrations.AlterField(
            model_name='address',
            name='room',
            field=models.IntegerField(blank=True, null=True, verbose_name='помещение'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=50, verbose_name='улица'),
        ),
    ]
