# Generated by Django 3.0.8 on 2020-08-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200816_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='contact',
            new_name='contact_set',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='address',
            new_name='address_set',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='contact',
            new_name='contact_set',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='job_place',
            new_name='job_place_set',
        ),
        migrations.RenameField(
            model_name='good',
            old_name='type',
            new_name='type_set',
        ),
        migrations.RenameField(
            model_name='good',
            old_name='unit',
            new_name='unit_set',
        ),
        migrations.RenameField(
            model_name='goodcategory',
            old_name='subject_area',
            new_name='subject_area_set',
        ),
        migrations.RenameField(
            model_name='goodcost',
            old_name='currency',
            new_name='currency_set',
        ),
        migrations.RenameField(
            model_name='goodcost',
            old_name='good_place',
            new_name='good_place_set',
        ),
        migrations.RenameField(
            model_name='goodcost',
            old_name='good',
            new_name='good_set',
        ),
        migrations.RenameField(
            model_name='goodcount',
            old_name='good_place',
            new_name='good_place_set',
        ),
        migrations.RenameField(
            model_name='goodcount',
            old_name='good',
            new_name='good_set',
        ),
        migrations.RenameField(
            model_name='goodplace',
            old_name='address',
            new_name='address_set',
        ),
        migrations.RenameField(
            model_name='goodplace',
            old_name='contact',
            new_name='contact_set',
        ),
        migrations.RenameField(
            model_name='goodplace',
            old_name='place_type',
            new_name='place_type_set',
        ),
        migrations.RenameField(
            model_name='goodtype',
            old_name='category',
            new_name='category_set',
        ),
        migrations.RenameField(
            model_name='phonenumber',
            old_name='contact',
            new_name='contact_set',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='contact',
            new_name='contact_set',
        ),
        migrations.AlterField(
            model_name='contact',
            name='passport',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
