# Generated by Django 3.0.10 on 2020-09-01 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200816_0117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'адрес', 'verbose_name_plural': 'адреса'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'контакт', 'verbose_name_plural': 'контакты'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'валюта', 'verbose_name_plural': 'валюты'},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name_plural': 'адрес электронной почты'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'сотрудник магазина', 'verbose_name_plural': 'сотрудники магазинов'},
        ),
        migrations.AlterModelOptions(
            name='good',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AlterModelOptions(
            name='goodcategory',
            options={'verbose_name': 'категория товара', 'verbose_name_plural': 'категории товаров'},
        ),
        migrations.AlterModelOptions(
            name='goodcost',
            options={'verbose_name': 'цена товара', 'verbose_name_plural': 'цены на товары'},
        ),
        migrations.AlterModelOptions(
            name='goodcount',
            options={'verbose_name': 'количество товара', 'verbose_name_plural': 'количество товаров'},
        ),
        migrations.AlterModelOptions(
            name='goodplace',
            options={'verbose_name': 'место расположения товара', 'verbose_name_plural': 'места расположения товаров'},
        ),
        migrations.AlterModelOptions(
            name='goodsubjectarea',
            options={'verbose_name': 'предметная область товара', 'verbose_name_plural': 'предметные области товаров'},
        ),
        migrations.AlterModelOptions(
            name='goodtype',
            options={'verbose_name': 'тип товара', 'verbose_name_plural': 'типы товаров'},
        ),
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'verbose_name': 'номер телефона', 'verbose_name_plural': 'номера телефонов'},
        ),
        migrations.AlterModelOptions(
            name='placetype',
            options={'verbose_name': 'тип места размещения товара', 'verbose_name_plural': 'типы мест размещения товаров'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'единица измерения', 'verbose_name_plural': 'единицы измерения'},
        ),
        migrations.AlterModelOptions(
            name='url',
            options={'verbose_name': 'ссылка', 'verbose_name_plural': 'ссылки'},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='address_set',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='contact_set',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='goodplace',
            old_name='address_set',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='goodplace',
            old_name='contact_set',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='email',
            name='contact_set',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='job_place_set',
        ),
        migrations.RemoveField(
            model_name='good',
            name='type_set',
        ),
        migrations.RemoveField(
            model_name='good',
            name='unit_set',
        ),
        migrations.RemoveField(
            model_name='goodcategory',
            name='subject_area_set',
        ),
        migrations.RemoveField(
            model_name='goodcost',
            name='currency_set',
        ),
        migrations.RemoveField(
            model_name='goodcost',
            name='good_place_set',
        ),
        migrations.RemoveField(
            model_name='goodcost',
            name='good_set',
        ),
        migrations.RemoveField(
            model_name='goodcount',
            name='good_place_set',
        ),
        migrations.RemoveField(
            model_name='goodcount',
            name='good_set',
        ),
        migrations.RemoveField(
            model_name='goodplace',
            name='place_type_set',
        ),
        migrations.RemoveField(
            model_name='goodtype',
            name='category_set',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='contact_set',
        ),
        migrations.RemoveField(
            model_name='url',
            name='contact_set',
        ),
        migrations.AddField(
            model_name='email',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.Contact', verbose_name='контакт'),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.GoodPlace', verbose_name='место работы'),
        ),
        migrations.AddField(
            model_name='good',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.GoodType', verbose_name='тип'),
        ),
        migrations.AddField(
            model_name='good',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.Unit', verbose_name='единица измерения'),
        ),
        migrations.AddField(
            model_name='goodcategory',
            name='subject_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.GoodSubjectArea', verbose_name='предметная область'),
        ),
        migrations.AddField(
            model_name='goodcost',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.Currency', verbose_name='валюта'),
        ),
        migrations.AddField(
            model_name='goodcost',
            name='good',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.Good', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='goodcost',
            name='good_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.GoodPlace', verbose_name='месторасположение товара'),
        ),
        migrations.AddField(
            model_name='goodcount',
            name='good',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.Good', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='goodcount',
            name='good_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.GoodPlace', verbose_name='местонахождение'),
        ),
        migrations.AddField(
            model_name='goodplace',
            name='place_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.PlaceType', verbose_name='тип места'),
        ),
        migrations.AddField(
            model_name='goodtype',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.GoodCategory'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.Contact', verbose_name='контакт'),
        ),
        migrations.AddField(
            model_name='url',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.Contact', verbose_name='контакт'),
        ),
    ]
