# Generated by Django 4.2.4 on 2023-08-25 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200901_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'адрес электронной почты', 'verbose_name_plural': 'адреса электронной почты'},
        ),
    ]
